// this file was generated automatically, so I decided not to edit
// the code at all, although only Web-related configs should be examined

// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyATbf-dqjMbNP84Kn6OaKDcy3n6yLnpgwk',
    appId: '1:628752812050:web:6c22c210f94478e43f70cb',
    messagingSenderId: '628752812050',
    projectId: 'appcheckweb',
    authDomain: 'appcheckweb.firebaseapp.com',
    storageBucket: 'appcheckweb.appspot.com',
    measurementId: 'G-PN1RZRV2WR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCPn7Ar51v9_bwFU7YvURABwphX1F1oguY',
    appId: '1:628752812050:android:877f0256b61ede743f70cb',
    messagingSenderId: '628752812050',
    projectId: 'appcheckweb',
    storageBucket: 'appcheckweb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAtXYHmaYfeFiCQ5A4MWf3kawmn4F35pQw',
    appId: '1:628752812050:ios:0952f3f9515420e13f70cb',
    messagingSenderId: '628752812050',
    projectId: 'appcheckweb',
    storageBucket: 'appcheckweb.appspot.com',
    iosClientId:
        '628752812050-09c6td7ma9iqp7lmkm69evoid0cai9vi.apps.googleusercontent.com',
    iosBundleId: 'com.example.appCheckWeb',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAtXYHmaYfeFiCQ5A4MWf3kawmn4F35pQw',
    appId: '1:628752812050:ios:0952f3f9515420e13f70cb',
    messagingSenderId: '628752812050',
    projectId: 'appcheckweb',
    storageBucket: 'appcheckweb.appspot.com',
    iosClientId:
        '628752812050-09c6td7ma9iqp7lmkm69evoid0cai9vi.apps.googleusercontent.com',
    iosBundleId: 'com.example.appCheckWeb',
  );
}
